version: '3.8'

services:
  backend:
    build: ./backend
    container_name: poke-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:12345678@postgres:5432/pokedb
      JWT_SECRET: supersecret
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: poke-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  postgres:
    image: postgres:15-alpine
    container_name: poke-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: pokedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
